[build]
target = ["riscv64gc-unknown-linux-gnu"]

[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-unknown-linux-gnu-gcc"
rustflags = [
  "-C",
  "link-args=-Wl,--dynamic-linker=/lib/ld-linux-riscv64-lp64d.so.1",
]
runner = "lima"
